### ISSUE TITLE
Use Vifm for saving attachments

### ISSUE THREAD

**Issue by gerazov** [anufrievroman/NeomuttFilePicker#2]
Awesome plugin :sunglasses: 

Can it be made to work for saving attached files as well?

**Comment by anufrievroman** [comment]
Interesting idea. Actually, I have this problem of saving all the time.
Theoretically, it should be possible. Instead of `vifm --choose-files` would need to use `vifm --choose-dir` to get the path from vifm and return it as some mutt command. I'll try to look into it.

I'll drop this line here, just to remember the save command:

`macro attach E <save-entry><kill-line>/home/gawron/attachments/<enter>`

**Comment by anufrievroman** [comment]
Hi, in #3 it has been implemented, although it requires several confirmations, but it seems to work.
